### ISSUE TITLE
[Q] if nothing found - nothing to recover?

### ISSUE THREAD

**Issue by laur89** [ianka/xfs_undelete#15]
This is more of a usage question.

Do I understand correctly something like

    ./xfs_undelete -i "" -o /mounted/flashdrive /dev/sdc1

would be a catch-all recovery - if that returns nothing (or not what expected), then data is lost?
I moved an empty dir over a data directory that needs to be recovered, but surprisingly only 2 binary files are found; fairly certain no writes were done to the filesystem after the event.

**Comment by ianka** [comment]
Yes, you used the tool correctly. So it did run from zero to 100% and only found those two files, yes?

Give me some time to investigate a similar test case.

**Comment by laur89** [comment]
> So it did run from zero to 100% and only found those two files, yes?

That's correct, 2 binary files, think some java or C# related ones.
Currently I'm running [this advice](https://unix.stackexchange.com/a/557432), and it definitely is finding configuration files I know to search for, confirming they're not overwritten.

**Comment by ianka** [comment]
That's the data blocks. Xfs_undelete scans the inode tree, and looks for deleted inode records instead, and only ever looks into data blocks listed in such a record.

My guess is it's too picky with that deleted inode magic in your case but I have to check this first.

You might want to try the other method and or use a tool as PhotoRec. It's much slower but it actually scans the whole filesystem for known data formats.

**Comment by laur89** [comment]
Cheers.
By PhotoRec, do you mean [testdisk](https://www.cgsecurity.org/wiki/TestDisk_Download)?

**Comment by laur89** [comment]
Finally mounted the partition, and... data had not been deleted. Unsure how that's possible, as an empty directory was moved over an existing directory with loads of files in there. No idea how, but data is actually intact.
Closing.

**Comment by ianka** [comment]
Uh. Ok. That explains it completely. Xfs_undelete ignores files that aren't actually deleted.
