### ISSUE TITLE
install on Suse 13.2

### ISSUE THREAD

**Issue by BrianCuttler** [ianka/xfs_undelete#16]
Fairly old OS, install failing to find xfs_undelete-master.

Any advice welcome.

thanks in advance, Brian

gyan:/tmp # zypper install xfs_undelete-master
Retrieving repository 'openSUSE:Factory' metadata ........................[done]
Building repository 'openSUSE:Factory' cache .............................[done]
Loading repository data...
Reading installed packages...
'xfs_undelete-master' not found in package names. Trying capabilities.
No provider of 'xfs_undelete-master' found.

**Comment by BrianCuttler** [comment]
Ah, its just a script, so I just ran it. Unfortunately it did not find any files to recover.
Are there other switches not listed, or any way to get a deeper search?
I simply used - # ./xfs_undelete  -o /usr20:recover /dev/sdc1
where /dev/sdc1 is the volume with the deleted files "/usr16" and /usr20 is actually not only a different volume, but NFS mounted as the other large volume on the local system doesn't have enough free space for the expected/hoped-for recovered files.
Yes, root has write access across  the nfs mount.

**Comment by ianka** [comment]
Did you umount the disk in question properly, or did you just unplug it? Because if the latter, the files maybe aren't actually deleted yet but still in the journal.

**Comment by BrianCuttler** [comment]
Jan,

Thank you for replying.

Attached multi disk raid array, has not been unplugged but ran the utility and found that because the drive has opened files I was unable to remount RO.
I killed jobs that I found via fuser, must have still been people # cd’d to the file system.
I rebooted, re-mounted RO and then ran the program.

Accidental delete was performed over NFS if that makes any difference in behavior.

Recovery was attempted on local system, system the raid is attached two.

Ext4 file system, approx. 66 Tbytes formatted, underlying structure is raid 60.

Thank you,
Brian

**Comment by ianka** [comment]
> **Ext4 file system**

This script is named **xfs**_undelete because it's for the **xfs** file system. For *ext4*, you need a different tool.

**Comment by BrianCuttler** [comment]
I misread or generalized, thanks for clearing that up.

**Comment by ianka** [comment]
So I can close this issue as resolved here, yes? Sorry.

**Comment by BrianCuttler** [comment]
Yes, my bad, thank you for the oversite.
