### ISSUE TITLE
"Your  stat  utility does not support the %m format option."

### ISSUE THREAD

**Issue by DamienLee2017** [ianka/xfs_undelete#18]
"Your  stat  utility does not support the %m format option."
what can i do?

**Comment by ianka** [comment]
On which OS / Linux distribution you are trying to use xfs_undelete? What does

    $ LANG=C stat --version

say?

**Comment by ianka** [comment]
You could help yourself by commenting out [lines 465–474](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L465-L474)  of the script. These are the only lines that use the problematic function. Their purpose is to prevent you from accidentally using an output directory within the source filesystem — that would overwrite the files you wanted to recover.

If you take extra care that you don't do such a stupid mistake, you don't need those lines.

**Comment by DamienLee2017** [comment]
> On which OS / Linux distribution you are trying to use xfs_undelete? What does
> 
> ```
> $ LANG=C stat --version
> ```
> 
> say?

stat (GNU coreutils) 8.4
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Michael Meskes

**Comment by ianka** [comment]
That one is pretty old, hmm. Go with my second advice then and take care about the output directory.

**Comment by DamienLee2017** [comment]
> You could help yourself by commenting out [lines 465–474](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L465-L474) of the script. These are the only lines that use the problematic function. Their purpose is to prevent you from accidentally using an output directory within the source filesystem — that would overwrite the files you wanted to recover.
> 
> If you take extra care that you don't do such a stupid mistake, you don't need those lines.

OK, I'll try. Thank you very much for your help.

**Comment by ianka** [comment]
Leave a comment if it worked.

**Comment by ianka** [comment]
You haven't replied for a week. I'm closing this issue. Feel free to reopen it if you have new information.
