### ISSUE TITLE
recovery not working on ubuntu

### ISSUE THREAD

**Issue by vot4anto** [ianka/xfs_undelete#19]
Hi,
 I try to use the tools on one xfs filesystem on ubuntu bionic with this command:
./xfs_undelete -i ""  /dev/mapper/lowspeed-das
Starting recovery.
Done.                              
but no files are recovered, the files are in one extensions hdf5 that is not listed if I use the -l option
Is I use strings command I can find some occurence, for example:
strings -td /dev/mapper/lowspeed-das | grep hdf5 
11817744 $/home/ldanciu/oqdata/calc_40597.hdf5

**Comment by ianka** [comment]
There is no error message so I wonder what's exactly wrong. Does it say `Checking  inode  83620415 ( 19%)` or similar during the recovery attempt?

> I use strings command I can find some occurence, for example:
> strings -td /dev/mapper/lowspeed-das | grep hdf5
> 11817744 $/home/ldanciu/oqdata/calc_40597.hdf5

It's entirely possible some of the data blocks of the deleted files haven't been reallocated, yet all the inodes already have. XFS unfortunately is sometimes very quick with reallocating used inodes and their data blocks.

**Comment by vot4anto** [comment]
Yes,
 it say something like checking inode during recovery attempt.

> It's entirely possible some of the data blocks of the deleted files haven't been reallocated, yet all the inodes already have. XFS unfortunately is sometimes very quick with reallocating used inodes and their data blocks.

I understand, so I don't have so much change to restore the files.
Please can you share with me some documentation about xsf behavior, because xfs.org is down.

Thanks

**Comment by ianka** [comment]
> Please can you share with me some documentation about xsf behavior

It's from my own observation.

> because xfs.org is down.

No, it isn't.

**Comment by ianka** [comment]
You haven't replied for a week. I'm closing this issue. Feel free to reopen it if you have new information.
