### ISSUE TITLE
Unclear program behavior

### ISSUE THREAD

**Issue by VijitCoder** [ianka/xfs_undelete#20]
I installed `tclsh` and `tcllib`. Copy-pasted your script, all set up, I suppose.

Fire up:
```sh
~ $ ./xfs_undelete.sh -t -1hour -r 'image/* /dev/sda3
> 
```
That's all I have. Just the prompt line. What is this supposed to mean?

FYI:
```sh
~ $ blkid
/dev/sda3: UUID="..." TYPE="xfs" PARTLABEL="home" PARTUUID="..."
```

**Comment by ianka** [comment]
> $ ./xfs_undelete.sh -t -1hour -r 'image/* /dev/sda3
>

You missed a closing tick behind the *. That's why the shell prompts a >

**Comment by VijitCoder** [comment]
Oh! Thanks.
