### ISSUE TITLE
no files recover generate in "-o dir" or  "./xfs_undeleted"

### ISSUE THREAD

**Issue by MyqueWooMiddo** [ianka/xfs_undelete#21]
Hello ianka 

    I install xfs_undelete tool correctly . I can run the command . 
    xfs_undelete locates in /data01/xfs_undelete-11.0 .  I copy a file to /data02/file_to_delete/test.txt with a few KB content.
    The mount point "/data02" is from device "/dev/sde1"
   I run the following command:

   cd /data01/xfs_undelete-11.0
  rm  -f /data02/file_to_delete/test.txt
  ./xfs_undelete /dev/sde1

  It shows "/dev/sde1 is currently mounted read-write. Trying to remount read-only.
Remount successful.
Starting recovery.
Done.                             1 (100%))
"

  I could not find the deleted file in " /data01/xfs_undelete-11.0/xfs_undeleted"

 If I add "-o /data01/recovery_test" para , I could not find deleted file in "/data01/recovery_test" . 

 The OS is Centos7.6.1810 x86_64 ,  tcl is 8.6.10 and tcllib is 1-20 , xfs_undelete is 11.0

**Comment by ianka** [comment]
First check if adding `-i ""` gives a different result. By default, only files that can be identified by the file utility are considered worth recovering.

The tool can also only recover a file when its inode record is marked deleted but isn't yet re-used and overwritten. Unfortunately, XFS is sometimes very quick with re-using inodes for new files.

**Comment by ianka** [comment]
You haven't replied for more than a week. I'm closing this issue. Feel free to reopen it if you have new information.
