### ISSUE TITLE
Please specify a block device or an XFS filesystem image

### ISSUE THREAD

**Issue by x-vibe** [ianka/xfs_undelete#22]
Hi there, I am hoping to recover a bunch of files but when running the command, I get:

**Please specify a block device or an XFS filesystem image.**

I run the command as follows, from the directory the tool is installed in:

**xfs_undelete  -t -10hour -r '*.jpg' -o /dev/disk/by/id/ata-xxx --no-remount-readonly /dev/disk/by/id/ata-xxx**

Infrastructure:

- unraid server with 8 disks XFS formatted, one of which is the parity disk.
- data was deleted on 6 disks, the 7th is the one I wish to restore to
- since deletion the server has not been written to
- array is mounted.

Would appreciate your steer, thanks for sharing such an awesome little program!

**Comment by ianka** [comment]
You are lucky that this did not work. Because you specified the output directory for the recovered files to be the disk you want to recover from. Specify an output **directory** on a **different** medium you have enough free space on.

Also, did you mean /dev/disk/**by-id**/ata-xxx?

    $ xfs_undelete -t -10hour -r '*.jpg' -o /mnt/my-temporary-storage/undeleted_files  --no-remount-readonly /dev/disk/by-id/ata-xxx

**Comment by ianka** [comment]
You haven't replied for more than a week. I'm closing this issue. Feel free to reopen it if you have new information.
