### ISSUE TITLE
using XFS v5 No files showing up

### ISSUE THREAD

**Issue by RonaldDuncan** [ianka/xfs_undelete#23]
Using XFS v5 
dmesg | grep XFS
[5536321.175489] XFS (sde1): Mounting V5 Filesystem

I deleted about 1tb of backups a few days ago, about 50 files and of course now need some back.

/dev/ssd is the block device where the files were deleted from and
/var/opt/mssql/restore is a new drive I have added to accept the recovered files.

./xfs_undelete -o /var/opt/mssql/restore /dev/sdd
/dev/sdd (/dev/sdd) is currently mounted read-write. Trying to remount read-only.
Remount successful.
Starting recovery.
Done.            

It took about 1 sec to run which seemed too fast, and the result was no files.
I am using Ubuntu, and untared the tar.gz installed TCL and LIBTCL and ran the ./xfs_undelete
I tried listing the file types and a few other commands.  I did not install xfs_undelete as a package.

**Comment by RonaldDuncan** [comment]
I tried a few other options
https://cnwrecovery.com/html/downloads.html - did not recognise the file system from windows
sudo apt install hxtools - Is meant to have a program xfs_irecover but it does not seem to be installed and is missing its manual entry.  There was a forum post by someone back in 2011 that managed to find the file and it did not work.
https://www.raisedr.com/download.php - Does seem to work and did find the deleted files.  I used the windows version with the drive accessible from a windows vm.  Took about 3 hours to scan disk.  Found most of the deleted files, unfortunately the directory I want is gone, which is not surprising since the disk was full prior to deletion, and after deletion I made another backup.
I have a snapshot of the drive, if you want to test to see why your program did not pick up the deleted files.

**Comment by ianka** [comment]
I wonder if you used the correct device node. Because

> 
> Using XFS v5
> dmesg | grep XFS
> [5536321.175489] XFS (sde1): Mounting V5 Filesystem

Here it says the filesystem is in a partition. /dev/sde1

But when you tried to recover, you used the whole disk /dev/sdd instead.

> ./xfs_undelete -o /var/opt/mssql/restore /dev/sdd

Something doesn't fit here.

**Comment by RonaldDuncan** [comment]
Thanks probably my mistake.

**Comment by RonaldDuncan** [comment]
Just rechecked, and /dev/sdd was the correct drive /dev/sde was an additional drive I added for the recovery data also XFS formatted the same way as /dev/sdd.
I have got a snapshot of the disk that we recovered the files from.  Typically we got everything back apart from the part I wanted.

**Comment by ianka** [comment]
_Mist!_
