### ISSUE TITLE
can't find package cmdline

### ISSUE THREAD

**Issue by my-petrichor** [ianka/xfs_undelete#24]
can't find package cmdline
    while executing
"package require cmdline"
    (file "./xfs_undelete" line 10)

**Comment by ianka** [comment]
You have to install the _tcllib_ distribution package. It includes this _cmdline_ tcl package.

**Comment by nickhuangxinyu** [comment]
I have the same questions, after i installed tcl with:
yum install -y tcl-devel tcl tcllib

it still failed with cmdline error

**Comment by ianka** [comment]
Check

    $ tclsh
    % package require cmdline

Does it throw an error as well? It's a bug in those distribution packages then. Which distribution is it?

**Comment by ianka** [comment]
You haven't replied for more than a week. I'm closing this issue. Feel free to reopen it if you have new information.

**Comment by mhmdar** [comment]
tcllib can't be found on centos8:

```
$ sudo yum install -y tcl-devel tcl tcllib
Last metadata expiration check: 1:21:02 ago on Wed 15 Feb 2023 03:35:13 PM UTC.
Package tcl-devel-1:8.6.8-2.el8.x86_64 is already installed.
Package tcl-1:8.6.8-2.el8.x86_64 is already installed.
No match for argument: tcllib
Error: Unable to find a match: tcllib
$
$ yum search tcllib
Last metadata expiration check: 1:19:47 ago on Wed 15 Feb 2023 03:36:42 PM UTC.
No matches found.
$
```

**Comment by ianka** [comment]
No idea why Centos8 does not have this package in its own repositories. You can use the Fedora EL8 package, I think. That should be the same as Centos8, I think.

https://kojipkgs.fedoraproject.org//packages/tcllib/1.19/3.el8/noarch/tcllib-1.19-3.el8.noarch.rpm

**Comment by mhmdar** [comment]
> tcllib can't be found on centos8:
> 
> ```
> $ sudo yum install -y tcl-devel tcl tcllib
> Last metadata expiration check: 1:21:02 ago on Wed 15 Feb 2023 03:35:13 PM UTC.
> Package tcl-devel-1:8.6.8-2.el8.x86_64 is already installed.
> Package tcl-1:8.6.8-2.el8.x86_64 is already installed.
> No match for argument: tcllib
> Error: Unable to find a match: tcllib
> $
> $ yum search tcllib
> Last metadata expiration check: 1:19:47 ago on Wed 15 Feb 2023 03:36:42 PM UTC.
> No matches found.
> $
> ```

It now works after installing `epel-release`:
```sh
$ sudo yum install -y epel-release
$ sudo yum install -y tcl-devel tcl tcllib
```

**Comment by ianka** [comment]
I'm happy that you found a solution for your problem.
