### ISSUE TITLE
xfs_undeleted only contains txt file?

### ISSUE THREAD

**Issue by nickhuangxinyu** [ianka/xfs_undelete#25]
I use xfs_undelete to recover my stupid rm-rf

my machine is centos 8 with lvm

i typed ./xfs_undelete /dev/mapper/cl-home

then it comes out:

```
Starting recovery.
Recovered file -> xfs_undeleted/2021-08-26-02-21_1474.txt
Recovered file -> xfs_undeleted/2021-08-26-02-21_150551.txt
```

it only output two txt file, which record some command history..

How to get the removed file?

**Comment by ianka** [comment]
Sometimes, the XFS filesystem is very quick in reallocating those inodes that have been marked as deleted. As xfs_undelete just walks the inode tree looking for inodes marked as deleted, it cannot find anything if they have been reused already.

If the inode was reused for a small file and the deleted file was huge, you might be lucky finding its unallocated data blocks with a tool as _photorec_ and if you are very lucky, you might be able to reconstruct parts of it.

That said, I used xfs_undelete under pressure a few times so far and it always found what was deleted accidentally. I think the main reason is that I have separate home and data filesystems on my machine, so system processes aren't continously creating new files in those filesystems.

**Comment by ianka** [comment]
You haven't replied for more than a week. I'm closing this issue. Feel free to reopen it if you have new information.
