### ISSUE TITLE
Error renaming to [...] to [...].pythonapplication/octet-stream

### ISSUE THREAD

**Issue by swalterfub** [ianka/xfs_undelete#28]
The program tries to rename to a filename with a slash:

> error renaming "xfs_undeleted/2021-11-30-12-56_21774193369" to "xfs_undeleted/2021-11-30-12-56_21774193369.pythonapplication/octet-stream": no such file or directory
    while executing
"file rename -force $of $rof"
    (procedure "investigateInodeBlock" line 93)
    invoked from within
"investigateInodeBlock $ag $iblock"
    (procedure "traverseInodeTree" line 40)
    invoked from within
"traverseInodeTree $ag $agi_branch"
    (procedure "traverseInodeTree" line 26)
    invoked from within
"traverseInodeTree $ag $agi_root"
    ("for" body line 10)
    invoked from within
"for {set ag 0} {$ag<$agcount} {incr ag} {
        ## Read inode B+tree information sector of this allocation group.
        seek $fd [expr {$blocksize*$agblocks*$ag..."
    (file "/root/xfs_undelete/xfs_undelete" line 598)

**Comment by ianka** [comment]
Yeah, it shouldn't do that. I think there's a problem parsing the output of ```file``` on your system. What does ```$ file --version``` say? What does ```$ file --brief --mime-type xfs_undeleted/2021-11-30-12-56_21774193369``` (or on any other binary file) say?

**Comment by ianka** [comment]
Unfortunately, I cannot debug your problem without your input. I'm closing this issue. Feel free to reopen it when you can provide the input I need.
