### ISSUE TITLE
How do I recover files?

### ISSUE THREAD

**Issue by uberhacker** [ianka/xfs_undelete#3]
This project looks promising but I'm confused how I should recover files.  It generated tons of files with the inode? as the filename.  How can I use these files to restore?

**Comment by ianka** [comment]
These are the restored files. XFS overwrites the filenames in directories on delete, so there's no way to get the filenames or the path back.

You can use e.g. the _file_ utility to guess the file type of an inodeXXXX file and then open the files with the correct application to check what's inside. Then rename and put them back. Ignore all those tons of recovered files you aren't interested in.

    $ cd xfs_undeleted
    $ file *

**Comment by ianka** [comment]
I revisited the XFS spec to see if I could help you. I found XFS sets the ctime field of a deleted inode to the deletion time. This can be used to limit the undelete operation to those files deletes since a specified time. I added that feature to xfs_undelete. See the new -t option.

**Comment by uberhacker** [comment]
Hey @ianka: I appreciate the feedback.  I was able to restore the files I deleted from backup but nice to see you are trying to help and improve the project.  Keep up the great work!

**Comment by ianka** [comment]
Will do. I close this issue as solved.
