### ISSUE TITLE
Restore file with big inode number fail

### ISSUE THREAD

**Issue by zzwwcc88** [ianka/xfs_undelete#32]
Hello, author!
My test scenario is to delete all files in the /testdir directory. During my test, I found that this tool cannot recover files with inode number jumps, which often occurs in multi-level directories, or files with larger inode numbers cannot be recovered. Even if the inode number is specified with the -s parameter, it cannot be recovered. For example, files with inode numbers of 50-110 can be restored, while files with numbers of 13581-13590 and 1069121-1069129 cannot be restored. How to solve this situation?

**Comment by ianka** [comment]
Could you describe the problem more in detail?

It's perfectly normal that inode numbers aren't consecutive. Xfs_undelete does not count those numbers up itself. Instead, it walks the inode tree and takes the inode numbers as identifiers only. If you use the -s option, you have to specify an existing inode number. As the tool still walks the tree from the very beginning but does not try to recover anything until that exact inode number specified is found.

**Comment by zzwwcc88** [comment]
Dear ianka, Hello!


My question is described in detail below. The operating system versions I tested are as follows:


Linux linuxz 3.10.0-957.axs7.x86_ 64 #1 SMP Sun May 24 08:42:07 CST 2020 x86_ 64 x86_ 64 x86_ 64 GNU/Linux


The directory structure I tested has the following two cases:
——————————————————situation one——————————————————
***@***.*** zwc]# ls -lirtR
.:
总用量 545296
&nbsp; &nbsp; &nbsp;67 drwxrwxr-x. 2 elastic elastic&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;6 7月&nbsp; 29 14:02 iamela
&nbsp; &nbsp; &nbsp;68 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6 7月&nbsp; 31 10:37 123.txt
&nbsp; &nbsp; &nbsp;69 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2 7月&nbsp; 31 10:37 1.txt
&nbsp; &nbsp; &nbsp;70 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2 7月&nbsp; 31 10:37 2.txt
&nbsp; &nbsp; &nbsp;71 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2 7月&nbsp; 31 10:37 3.txt
&nbsp; &nbsp; &nbsp;72 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3 7月&nbsp; 31 10:37 4.txt
&nbsp; &nbsp; &nbsp;73 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2 7月&nbsp; 31 10:37 5.txt
&nbsp; &nbsp; &nbsp;74 drwxr-xr-x. 2 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;4096 7月&nbsp; 31 10:37 abc
&nbsp; &nbsp; &nbsp;99 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; 26664 7月&nbsp; 31 10:37 abc.zip
&nbsp; &nbsp; 100 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1157 7月&nbsp; 31 10:37 anaconda-ks.cfg
&nbsp;524416 drwxr-xr-x. 2 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 219 7月&nbsp; 31 10:37 bcd
1069184 drwxr-xr-x. 2 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 269 7月&nbsp; 31 10:37 cef
&nbsp; &nbsp; 101 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp;69068800 7月&nbsp; 31 10:37 lib1.tar
&nbsp; &nbsp; 102 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; 473753600 7月&nbsp; 31 10:37 lib.tar
&nbsp; &nbsp; 103 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; 35149 7月&nbsp; 31 10:37 LICENSE
&nbsp; &nbsp; 104 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; 1170791 7月&nbsp; 31 10:37 log1.tar.bz
&nbsp; &nbsp; 105 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; 1170791 7月&nbsp; 31 10:37 log.tar.bz
&nbsp; &nbsp; 106 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; 1774599 7月&nbsp; 31 10:37 log.tar.gz
&nbsp; &nbsp; 107 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112 7月&nbsp; 31 10:37 loop-test.sh
&nbsp; &nbsp; 108 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; 28499 7月&nbsp; 31 10:37 messages
&nbsp; &nbsp; 109 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp;271793 7月&nbsp; 31 10:37 messages-20220410
&nbsp; &nbsp; 110 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp;628163 7月&nbsp; 31 10:37 messages-20220421
&nbsp; &nbsp; 111 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp;408352 7月&nbsp; 31 10:37 messages-20220424
&nbsp; &nbsp; 112 -rw-------. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp;674055 7月&nbsp; 31 10:37 messages-20220501
1732704 drwxr-xr-x. 2 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 219 7月&nbsp; 31 10:37 pgarch
&nbsp; &nbsp; 113 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; 12538 7月&nbsp; 31 10:37 README.md
&nbsp; &nbsp; 114 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; 1739411 7月&nbsp; 31 10:37 report.xml
&nbsp; &nbsp; 115 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 150 7月&nbsp; 31 10:37 shell.nix
&nbsp; &nbsp; 116 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; 7482378 7月&nbsp; 31 10:37 testdisk-7.2-WIP.linux26-x86_64.tar.bz2
&nbsp; &nbsp; 117 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.1.log
&nbsp; &nbsp; 120 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.4.log
&nbsp; &nbsp; 119 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.3.log
&nbsp; &nbsp; 118 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.2.log
&nbsp; &nbsp; 123 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.7.log
&nbsp; &nbsp; 122 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.6.log
&nbsp; &nbsp; 121 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.5.log
&nbsp; &nbsp; 126 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.log
&nbsp; &nbsp; 125 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.9.log
&nbsp; &nbsp; 124 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.8.log
&nbsp; &nbsp; 127 -rw-r--r--. 1 root&nbsp; &nbsp; root&nbsp; &nbsp; &nbsp; &nbsp; 26664 7月&nbsp; 31 10:37 xfs_undelete-master.zip


./iamela:
总用量 0


./abc:
总用量 3788
75 -rw-------. 1 root root&nbsp; &nbsp;27469 7月&nbsp; 31 10:37 messages
76 -rw-r--r--. 1 root root&nbsp; &nbsp;35149 7月&nbsp; 31 10:37 LICENSE
78 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;150 7月&nbsp; 31 10:37 shell.nix
77 -rw-r--r--. 1 root root&nbsp; &nbsp;12538 7月&nbsp; 31 10:37 README.md
79 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 31 10:37 1.txt
80 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 31 10:37 2.txt
81 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 31 10:37 3.txt
82 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; &nbsp;3 7月&nbsp; 31 10:37 4.txt
83 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 31 10:37 5.txt
84 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.1.log
86 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.3.log
85 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.2.log
87 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.4.log
88 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.5.log
89 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.6.log
91 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.8.log
90 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.7.log
93 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.log
92 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 31 10:37 vmware-network.9.log
94 -rw-------. 1 root root&nbsp; 271793 7月&nbsp; 31 10:37 messages-20220410
95 -rw-------. 1 root root&nbsp; 628163 7月&nbsp; 31 10:37 messages-20220421
96 -rw-------. 1 root root&nbsp; 408352 7月&nbsp; 31 10:37 messages-20220424
97 -rw-------. 1 root root&nbsp; 674055 7月&nbsp; 31 10:37 messages-20220501
98 -rw-r--r--. 1 root root 1739411 7月&nbsp; 31 10:37 report.xml


./bcd:
总用量 138972
524417 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.1.log
524418 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.2.log
524420 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.4.log
524419 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.3.log
524421 -rw-r--r--. 1 root root&nbsp; 1774599 7月&nbsp; 31 10:37 log.tar.gz
524422 -rw-r--r--. 1 root root&nbsp; 1170791 7月&nbsp; 31 10:37 log.tar.bz
524423 -rw-r--r--. 1 root root 69068800 7月&nbsp; 31 10:37 lib.tar
524424 -rw-r--r--. 1 root root&nbsp; &nbsp; 26664 7月&nbsp; 31 10:37 abc.zip
524425 -rw-r--r--. 1 root root&nbsp; 1170791 7月&nbsp; 31 10:37 log1.tar.bz
524426 -rw-r--r--. 1 root root 69068800 7月&nbsp; 31 10:37 lib1.tar


./cef:
总用量 44
1069185 -rw-r--r--. 1 root root&nbsp; &nbsp;57 7月&nbsp; 31 10:37 ld
1069187 -rw-r--r--. 1 root root&nbsp; 689 7月&nbsp; 31 10:37 mta
1069186 -rw-r--r--. 1 root root&nbsp; 101 7月&nbsp; 31 10:37 libnssckbi.so.x86_64
1069190 ----r-xr-x. 1 root root&nbsp; &nbsp;32 7月&nbsp; 31 10:37 secret_key
1069189 -rw-r--r--. 1 root root&nbsp; &nbsp;68 7月&nbsp; 31 10:37 NetworkManager.state
1069188 -rw-r--r--. 1 root root&nbsp; 939 7月&nbsp; 31 10:37 NetworkManager-intern.conf
1069191 -rw-r--r--. 1 root root&nbsp; &nbsp;61 7月&nbsp; 31 10:37 timestamps
1069193 -rw-r--r--. 1 root root&nbsp; 312 7月&nbsp; 31 10:37 a0241666-9184-4733-814d-7bba844a10ae.InvIndex
1069192 -rw-r--r--. 1 root root 5080 7月&nbsp; 31 10:37 8fee3326-1637-4113-8fd5-70819d7ddb4d.StObj
1069194 -rw-r--r--. 1 root root&nbsp; 576 7月&nbsp; 31 10:37 fstab


./pgarch:
总用量 138972
1732705 -rw-r--r--. 1 root root&nbsp; &nbsp; 26664 7月&nbsp; 31 10:37 abc.zip
1732706 -rw-r--r--. 1 root root 69068800 7月&nbsp; 31 10:37 lib1.tar
1732707 -rw-r--r--. 1 root root 69068800 7月&nbsp; 31 10:37 lib.tar
1732708 -rw-r--r--. 1 root root&nbsp; 1170791 7月&nbsp; 31 10:37 log1.tar.bz
1732709 -rw-r--r--. 1 root root&nbsp; 1170791 7月&nbsp; 31 10:37 log.tar.bz
1732710 -rw-r--r--. 1 root root&nbsp; 1774599 7月&nbsp; 31 10:37 log.tar.gz
1732711 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.1.log
1732713 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.3.log
1732712 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.2.log
1732714 -rw-r--r--. 1 root root&nbsp; &nbsp; &nbsp; 734 7月&nbsp; 31 10:37 vmware-network.4.log

——————————————————situation two——————————————————
***@***.*** tmp]# cat lsinfo.txt&nbsp;
.:
总用量 1583736
&nbsp; &nbsp; &nbsp;67 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 6 7月&nbsp; 21 22:28 123.txt
&nbsp; &nbsp; 102 drwxr-xr-x 2 root root&nbsp; &nbsp; &nbsp; &nbsp;4096 7月&nbsp; 21 22:28 abc
&nbsp; &nbsp; &nbsp;68 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194924 7月&nbsp; 21 22:28 amba10.tar.bz
&nbsp; &nbsp; &nbsp;69 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194924 7月&nbsp; 21 22:28 amba10.tar.gz
&nbsp; &nbsp; &nbsp;70 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;195489 7月&nbsp; 21 22:28 amba11.tar.bz
&nbsp; &nbsp; &nbsp;71 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;195489 7月&nbsp; 21 22:28 amba11.tar.gz
&nbsp; &nbsp; &nbsp;72 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194648 7月&nbsp; 21 22:28 amba12.tar.bz
&nbsp; &nbsp; &nbsp;73 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194648 7月&nbsp; 21 22:28 amba12.tar.gz
&nbsp; &nbsp; &nbsp;74 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194648 7月&nbsp; 21 22:28 amba13.tar.bz
&nbsp; &nbsp; &nbsp;75 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 99497 7月&nbsp; 21 22:28 amba14.tar.bz
&nbsp; &nbsp; &nbsp;76 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 99111 7月&nbsp; 21 22:28 amba15.tar.bz
&nbsp; &nbsp; &nbsp;77 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 99658 7月&nbsp; 21 22:28 amba16.tar.bz
&nbsp; &nbsp; &nbsp;78 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 70427 7月&nbsp; 21 22:28 amba17.tar.bz
&nbsp; &nbsp; &nbsp;79 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 41330 7月&nbsp; 21 22:28 amba18.tar.bz
&nbsp; &nbsp; &nbsp;80 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 41400 7月&nbsp; 21 22:28 amba19.tar.bz
&nbsp; &nbsp; &nbsp;81 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194754 7月&nbsp; 21 22:28 amba1.tar.bz
&nbsp; &nbsp; &nbsp;82 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;194754 7月&nbsp; 21 22:28 amba1.tar.gz
&nbsp; &nbsp; &nbsp;83 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999701 7月&nbsp; 21 22:28 ambari-alerts.log.1
&nbsp; &nbsp; &nbsp;84 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999516 7月&nbsp; 21 22:28 ambari-alerts.log.10
&nbsp; &nbsp; &nbsp;85 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999701 7月&nbsp; 21 22:28 ambari-alerts.log.11
&nbsp; &nbsp; &nbsp;86 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999746 7月&nbsp; 21 22:28 ambari-alerts.log.12
&nbsp; &nbsp; &nbsp;87 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999942 7月&nbsp; 21 22:28 ambari-alerts.log.13
&nbsp; &nbsp; &nbsp;88 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999988 7月&nbsp; 21 22:28 ambari-alerts.log.14
&nbsp; &nbsp; &nbsp;89 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999628 7月&nbsp; 21 22:28 ambari-alerts.log.15
&nbsp; &nbsp; &nbsp;90 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999731 7月&nbsp; 21 22:28 ambari-alerts.log.16
&nbsp; &nbsp; &nbsp;91 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999785 7月&nbsp; 21 22:28 ambari-alerts.log.17
&nbsp; &nbsp; &nbsp;92 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999643 7月&nbsp; 21 22:28 ambari-alerts.log.18
&nbsp; &nbsp; &nbsp;93 -rw-r--r-- 1 root root&nbsp; &nbsp; 9999498 7月&nbsp; 21 22:28 ambari-alerts.log.19
&nbsp; &nbsp; &nbsp;94 -rw------- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;1157 7月&nbsp; 21 22:28 anaconda-ks.cfg
8388672 drwxr-xr-x 2 root root&nbsp; &nbsp; &nbsp; &nbsp; 118 7月&nbsp; 21 22:28 bcd
&nbsp; &nbsp; &nbsp;95 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp; 112 7月&nbsp; 21 22:28 loop-test.sh
&nbsp; &nbsp; &nbsp;96 -rw------- 1 root root&nbsp; &nbsp; &nbsp; 28499 7月&nbsp; 21 22:28 messages
&nbsp; &nbsp; &nbsp;97 -rw-r--r-- 1 root root&nbsp; &nbsp;14473295 7月&nbsp; 21 22:28 osw.tar.gz
&nbsp; &nbsp; &nbsp;98 -rw-r--r-- 1 root root 1290229760 7月&nbsp; 21 22:28 recup_dir.1.tar
&nbsp; &nbsp; &nbsp;99 -rw-r--r-- 1 root root&nbsp; &nbsp; 7482378 7月&nbsp; 21 22:28 testdisk-7.2-WIP.linux26-x86_64.tar.bz2
&nbsp; &nbsp; 100 -rw-r--r-- 1 root root&nbsp; 197213784 7月&nbsp; 21 22:28 var.tar.gz
&nbsp; &nbsp; 101 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; 26664 7月&nbsp; 21 22:28 xfs_undelete-master.zip


./abc:
总用量 3788
103 -rw------- 1 root root&nbsp; &nbsp;27469 7月&nbsp; 21 22:28 messages
104 -rw-r--r-- 1 root root&nbsp; &nbsp;35149 7月&nbsp; 21 22:28 LICENSE
105 -rw-r--r-- 1 root root&nbsp; &nbsp;12538 7月&nbsp; 21 22:28 README.md
106 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;150 7月&nbsp; 21 22:28 shell.nix
107 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 21 22:28 1.txt
109 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 21 22:28 3.txt
108 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 21 22:28 2.txt
111 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;2 7月&nbsp; 21 22:28 5.txt
110 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp; &nbsp;3 7月&nbsp; 21 22:28 4.txt
112 -rw-r--r-- 1 root root 1739411 7月&nbsp; 21 22:28 report.xml
113 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.1.log
116 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.4.log
115 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.3.log
114 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.2.log
120 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.8.log
119 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.7.log
118 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.6.log
117 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.5.log
121 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.9.log
122 -rw-r--r-- 1 root root&nbsp; &nbsp; &nbsp;734 7月&nbsp; 21 22:28 vmware-network.log
123 -rw------- 1 root root&nbsp; 271793 7月&nbsp; 21 22:28 messages-20220410
124 -rw------- 1 root root&nbsp; 628163 7月&nbsp; 21 22:28 messages-20220421
125 -rw------- 1 root root&nbsp; 408352 7月&nbsp; 21 22:28 messages-20220424
126 -rw------- 1 root root&nbsp; 674055 7月&nbsp; 21 22:28 messages-20220501


./bcd:
总用量 16
8388674 -rw-r--r-- 1 root root 734 7月&nbsp; 21 22:28 vmware-network.2.log
8388673 -rw-r--r-- 1 root root 734 7月&nbsp; 21 22:28 vmware-network.1.log
8388676 -rw-r--r-- 1 root root 734 7月&nbsp; 21 22:28 vmware-network.4.log
8388675 -rw-r--r-- 1 root root 734 7月&nbsp; 21 22:28 vmware-network.3.log





In the tests of the above two cases, only files with small and continuous inode sequence numbers can be recovered (such as inode67-inode127). Even if -s is used to specify inode sequence numbers, inode files with large sequence numbers cannot be recovered. The recovery command is/ xfs_ Undelete /dev/vgxx/lvxx has no parameters. Please also check whether this problem has occurred and what solutions are available. Thanks, best regards



该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ianka/xfs_undelete"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ianka/xfs_undelete] Restore file with big inode number fail (Issue #32)





 
Could you describe the problem more in detail?
 
It's perfectly normal that inode numbers aren't consecutive. Xfs_undelete does not count those numbers up itself. Instead, it walks the inode tree and takes the inode numbers as identifiers only. If you use the -s option, you have to specify an existing inode number. As the tool still walks the tree from the very beginning but does not try to recover anything until that exact inode number specified is found.

**Comment by ianka** [comment]
Xfs_undelete does not care about directories. The inode tree is a separate structure.

You don't need the -s option for those tests. It's meant to pick up an interrupted recovery at some existing inode number that had been printed during the interrupted run. So you can recover in multiple batches e.g. if your output directory is on a rather small USB stick. If you point -s to an inode number, it won't start the inode tree walk at that point —that's simply not possible— but walk the whole tree and simply not recover any files before that one inode with the number specified with -s has been passed during the walk.

_The inode tree is always walked in its entirety._ (Unless you interrupt the recovery run.)

I understood that in your test environment, some files could be recovered, and those tend to have small inode numbers, and their inode numbers tend to be consecutive.

That's unfortunately not enough information to look for a specific bug. Do you have more clues for me?

**Comment by zzwwcc88** [comment]
What information can I collect to help you analyze this problem？
message，xfs_info,and what?




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ianka/xfs_undelete"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ianka/xfs_undelete] Restore file with big inode number fail (Issue #32)





 
Xfs_undelete does not care about directories. The inode tree is a separate structure.
 
You don't need the -s option for those tests. It's meant to pick up an interrupted recovery at some existing inode number that had been printed during the interrupted run. So you can recover in multiple batches e.g. if your output directory is on a rather small USB stick. If you point -s to an inode number, it won't start the inode tree walk at that point —that's simply not possible— but walk the whole tree and simply not recover any files before that one inode with the number specified with -s has been passed during the walk.
 
The inode tree is always walked in its entirety. (Unless you interrupt the recovery run.)
 
I understood that in your test environment, some files could be recovered, and those tend to have small inode numbers, and their inode numbers tend to be consecutive.
 
That's unfortunately not enough information to look for a specific bug. Do you have more clues for me?

**Comment by ianka** [comment]
Unfortunately, I have been unable to find a solution to your problem. Sorry.

I'm closing this issue. Feel free to reopen if you have new information.
