### ISSUE TITLE
Test file not recovered, what am I doing wrong?

### ISSUE THREAD

**Issue by GenAIGator** [ianka/xfs_undelete#34]
Test file not recovered, what am I doing wrong?

It should have recovered text.txt but when I check xfs_undeleted/ its empty.

```
[root@ip-10-0-10-221 xfs_undelete]# df |grep new
/dev/xvdf1       8376300 1269792   7106508  16% /newdrive

[root@ip-10-0-10-221 xfs_undelete]# echo "test" >/newdrive/text.txt
[root@ip-10-0-10-221 xfs_undelete]# cat /newdrive/text.txt
test

[root@ip-10-0-10-221 xfs_undelete]# rm -f /newdrive/text.txt
[root@ip-10-0-10-221 xfs_undelete]# umount /newdrive
[root@ip-10-0-10-221 xfs_undelete]# df |grep newdrive

[root@ip-10-0-10-221 xfs_undelete]# ./xfs_undelete /dev/xvdf1
Starting recovery.
Done.

[root@ip-10-0-10-221 xfs_undelete]# ls xfs_undeleted/
[root@ip-10-0-10-221 xfs_undelete]#
```

**Comment by ianka** [comment]
I'm not entirely sure, unfortunately. Someone brought up via email that some older XFS file systems have a slightly different signature for deleted files in their inodes. I have to check it.

**Comment by lelik77** [comment]
I have xfs raid-5 array mounted as /srv/media
root@myserver:~# df -h 
/dev/md3         19T   17T  1.9T  90% /srv/media

root@myserver:~# cat /proc/mdstat
md3 : active raid5 sdg5[6] sde5[2] sdf5[5] sdd5[9] sdb5[8] sdc5[7]
      19506902080 blocks super 1.2 level 5, 64k chunk, algorithm 2 [6/6] [UUUUUU]
	  
root@myserver:~# lsblk -o PATH,FSTYPE,MOUNTPOINT /dev/md3
PATH     FSTYPE MOUNTPOINT
/dev/md3 xfs    /srv/media

Accidentally deleted a folder using rm (intended to delete a soft link).

Mounted an external drive :

root@myserver:~# lsblk -o PATH,FSTYPE,MOUNTPOINT /dev/sda1
PATH      FSTYPE MOUNTPOINT
/dev/sda1 ext4   /root/recovery

Cloned your script using git. 
Made sure all per-requisits are met:
tcl >= 8.6
    tcllib
    GNU coreutils
    file (having magic number files with MIME type support)

Run 
root@myserver:~# ./xfs_undelete -t 2023-05-01 -o /root/recovery/ /dev/md3
Got:
Starting recovery.
Done.

But process went way too fast for 18Tb and 0 files were recovered.

**Comment by ianka** [comment]
Please follow the new issue.
