### ISSUE TITLE
who can help me recover some files in a plesk system?

### ISSUE THREAD

**Issue by agaitan26** [ianka/xfs_undelete#40]
who can help me recover some files in a plesk system?

**Comment by ianka** [comment]
Plesk is a web frontend for administration purposes.

For using xfs_undelete, you need access to a ssh console on that machine, and need the permissions to read the raw XFS filesystem the lost files are on.

**Comment by agaitan026** [comment]
Yes I got all that just need help I can pay

**Comment by ianka** [comment]
I don't offer paid services. Sorry.
