### ISSUE TITLE
recovering a vdisk.img file

### ISSUE THREAD

**Issue by alturismo** [ianka/xfs_undelete#41]
Hi, i also accidently wiped a VM including image ... so i ended up here now ;)

i tried following the instructions

```root@AlsServer:/tmp# ./xfs_undelete.sh -t -11hour -i "" /dev/nvme1n1p1
Starting recovery.
Recovered file -> xfs_undeleted/2023-03-03-08-24_1092962809.bin
Recovered file -> xfs_undeleted/2023-03-03-08-24_1098416061.bin
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304231.gzip
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304236.bin
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304237.txt
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304240.txt
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304241.pgp
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304243.txt
Recovered file -> xfs_undeleted/2023-03-03-08-24_1152304250.pgp
Recovered file -> xfs_undeleted/2023-03-03-09-03_2165197241.bin
Recovered file -> xfs_undeleted/2023-03-03-08-24_3221231872.txt
Done.
root@AlsServer:/tmp#`

it does fairly work, but there is no vdisk.img with 120 GB in size, so i assume im also too late and xfs already reaccolerated the free space ... even there where definately no writes afterwards.

may possible as .img is also not included in the mime type list (-l function) ? the list is huge, but .img is not included ...

the disk is unmounted

```root@AlsServer:/tmp# mount | grep -i "nvme"
root@AlsServer:/tmp#`

if you have any other advice ;) thanks ahead, also tried the -r option but then the results are even less.

**Comment by ianka** [comment]
It's possible that your `file` utility doesn't know the filetype of the image. By default, xfs_undelete does not recover such files as they are likely bogus. Try again with the `-i ""` option. (not -r!) That sets the ignore list to empty and all file types are considered worth recovering, even those `file` does not know.

**Comment by alturismo** [comment]
> Try again with the `-i ""` option. (not -r!) That sets the ignore list to empty and all file types are considered worth recovering, even those `file` does not know.

ohh, seems i didnt really wrote it properly ;) i did indeed and the upper result is from -i "", -r gives even less results, nevertheless, been worth a try and i redid the presantation which was hanging in that VM ;)

at least i know there is a tool and it works in some cases, seems just its bounded to the mime filetypes.

thanks for the Tipp anyway, but i went throug hyour nice docu and tried all these cases, just wasnt so clear that it relies on the mime filetypes, so for my understanding, as  *.img  is not listed there, it never would work for those files, correct ?

**Comment by ianka** [comment]
I does not rely on those filetypes but it tries to give some more filter options depending on the filetype. As most people know they are only interested in that one pdf or similar they deleted and not a ton of binary files. Img is not listed because your `file` utility does not tell a corresponding mime type.

**Comment by alturismo** [comment]
thanks for the input and specially thanks for this nice script !!!
