### ISSUE TITLE
I have xfs raid-5 array mounted as /srv/media

### ISSUE THREAD

**Issue by ianka** [ianka/xfs_undelete#43]
I have xfs raid-5 array mounted as /srv/media
root@myserver:~# df -h 
/dev/md3         19T   17T  1.9T  90% /srv/media

root@myserver:~# cat /proc/mdstat
md3 : active raid5 sdg5[6] sde5[2] sdf5[5] sdd5[9] sdb5[8] sdc5[7]
      19506902080 blocks super 1.2 level 5, 64k chunk, algorithm 2 [6/6] [UUUUUU]
	  
root@myserver:~# lsblk -o PATH,FSTYPE,MOUNTPOINT /dev/md3
PATH     FSTYPE MOUNTPOINT
/dev/md3 xfs    /srv/media

Accidentally deleted a folder using rm (intended to delete a soft link).

Mounted an external drive :

root@myserver:~# lsblk -o PATH,FSTYPE,MOUNTPOINT /dev/sda1
PATH      FSTYPE MOUNTPOINT
/dev/sda1 ext4   /root/recovery

Cloned your script using git. 
Made sure all per-requisits are met:
tcl >= 8.6
    tcllib
    GNU coreutils
    file (having magic number files with MIME type support)

Run 
root@myserver:~# ./xfs_undelete -t 2023-05-01 -o /root/recovery/ /dev/md3
Got:
Starting recovery.
Done.

But process went way too fast for 18Tb and 0 files were recovered.

_Originally posted by @lelik77 in https://github.com/ianka/xfs_undelete/issues/34#issuecomment-1635289038_

**Comment by ianka** [comment]
Which version of xfs_undelete do you use? Older versions had been more picky on what is considered a deleted inode. Does it recover something if you leave out the -t option?

Also, the walk through the inode tree should be reasonably fast. It does not touch the whole disk. Only that tree, and the files to recover.

**Comment by lelik77** [comment]
I used git clone to pull from git, I guess latest you have.

Header of the script says version 3 from 2019?

root@myserver:~# cat xfs_undelete | head -c 200

```
#!/usr/bin/env tclsh
##
## Copyright (c) 2019 Jan Kandziora <jjj@gmx.de>
##
## This source code is licensed under the GNU General Public License,
## Version 3. See the file COPYING for more details.

```
And Yes, tried without -t option, yields 0 files as well, same speed.

**Comment by ianka** [comment]
Hmm. Unfortunately the XFS filesystem has lots and lots of versions and options and that makes it hard to track down the problem. If it finds zero deleted files regardless what you do, its likely that the brach/leaf markers in the inode tree or the inodes itself are slightly different to what the documentation says. So xfs_undelete cannot make sense of that information.

I think in your case the culprit could be the inode btree magic. This one is checked from line 297 of the script.

You could insert a `puts stderr [string range $data 0 3]` in a new line before the `switch` statement and check what it says for your filesystem.

**Comment by lelik77** [comment]
```
root@myserver:~/xfs_undelete#  ./xfs_undelete -t 2023-03-01 -o /root/recovery /dev/md3
/dev/md3 (/dev/md3) is currently mounted read-write. Trying to remount read-only.
Remount successful.
Starting recovery.
IABT
IABT
IABTking  inode          0 (  2%)88 (  2%))
IABTking  inode          0 (  3%)91 (  3%))
IABT
IABTking  inode          0 (  5%)23 (  5%))
IABTking  inode          0 (  6%)%)6%) 6%))
IABT
IABTking  inode    6226176 (  8%)10 (  8%))
IABTking  inode          0 (  9%)92 (  9%))
IABTking  inode          0 ( 10%)( 10%)0%))
...
IABTking  inode 3905240333325330803 ( 99%))
IABTking  inode          0 ( 99%)92 ( 99%))
IABTking  inode          0 ( 99%)84 ( 99%))
IABTking  inode          0 (100%)52 (100%))
Done.
```

**Comment by ianka** [comment]
IABT. So, nothing special here. It was worth a try though. … I'm out of ideas at this point.

**Comment by ianka** [comment]
Unfortunately, I have been unable to find a solution to your problem. Sorry.

I'm closing this issue. Feel free to reopen if you have new information.

**Comment by ianka** [comment]
I'm closing this issue. Feel free to reopen if you have new information.
