### ISSUE TITLE
missing value to go with key(  0%)

### ISSUE THREAD

**Issue by jalapenopuzzle** [ianka/xfs_undelete#46]
When I try to run xfs_undelete on v13.0 release, it fails with a stack trace:

Commit v13.0 CommitID 43fec30088d4bdc608a43a1aa81f2525dd260d17

[root@host xfs_undelete]# /root/XFS_Data_Recovery/xfs_undelete/xfs_undelete/xfs_undelete -i "" -t 2024-01-09 /dev/mapper/rhel-data
Starting recovery.
missing value to go with key(  0%)
    while executing
"dict get $extent count"
    ("uplevel" body line 2)
    invoked from within
"uplevel 1 $body"
    (procedure "lmap" line 4)
    invoked from within
"lmap {loffset extent} $extents {
			expr {$::blocksize*($loffset+[dict get $extent count])}
		}"
    (procedure "investigateInodeBlock" line 87)
    invoked from within
"investigateInodeBlock $ag $iblock"
    (procedure "traverseInodeTree" line 40)
    invoked from within
"traverseInodeTree $ag $agi_branch"
    (procedure "traverseInodeTree" line 26)
    invoked from within
"traverseInodeTree $ag $agi_root"
    ("for" body line 10)
    invoked from within
"for {set ag 0} {$ag<$agcount} {incr ag} {
	## Read inode B+tree information sector of this allocation group.
	seek $fd [expr {$blocksize*$agblocks*$ag..."
    (file "/root/XFS_Data_Recovery/xfs_undelete/xfs_undelete/xfs_undelete" line 661)
[root@host xfs_undelete]# 

I note that CommitID 43fec30088d4bdc608a43a1aa81f2525dd260d17 v13.0 introduced the code at
"lmap {loffset extent} $extents {
			expr {$::blocksize*($loffset+[dict get $extent count])}
		}"
    (procedure "investigateInodeBlock" line 87)

Testing the parent commit:

CommitID 6176de1770ab838f715abf5daf82aab9e390bbef

[root@host xfs_undelete]# /root/XFS_Data_Recovery/xfs_undelete/xfs_undelete/xfs_undelete -i "" -t 2024-01-09 /dev/mapper/rhel-data
Starting recovery.
Recovered file -> xfs_undeleted/2024-01-09-09-43_11252188.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_11252190.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_11252191.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800488.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800489.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800490.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800491.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800498.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800499.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800500.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800502.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800503.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800504.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800505.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800506.bin
Recovered file -> xfs_undeleted/2024-01-09-09-43_16800507.bin
...

This appears to be working as advertised.

So it seems that CommitID 43fec30088d4bdc608a43a1aa81f2525dd260d17 is broken.

**Comment by ianka** [comment]
Ahh, that lmap replacement for Tcl-8.5 compatibility was too naive for the function I later introduced to support filtering for a maximum file size. … That's what happens if you test things only when you introduce it.

I fixed it. I think. Could you please try the latest commit?

**Comment by jalapenopuzzle** [comment]
I confirm that v13.1 commit c01b5fac55966a517f40a4aa3c3593e7f061502f has fixed the problem.
Thank you for your fanatical support!

**Comment by ianka** [comment]
You are welcome.
