### ISSUE TITLE
Script constantly drops dd warnings.

### ISSUE THREAD

**Issue by cab404** [ianka/xfs_undelete#5]
```dd: cannot seek: Value too large for defined data type```

I am not yet sure, whether that affects the data, but sure looks scary.

**Comment by cab404** [comment]
Okay, several generated files are sparse 300TB+ zero-filled blobs :D

**Comment by ianka** [comment]
There are some sanity checks on the extents found in an inode, but it seems we can't catch all insanity happening. Such sparse files are valid and may have resided in a much smaller source filesystem.

Any ideas on how to sort those extents out?

**Comment by cab404** [comment]
> Any ideas on how to sort those extents out?

I guess we can add an option to not retrieve files > some size. And that file size should probably be less than a uintmax_t (usually 64 bits, I think -.-), used by dd :D

**Comment by ianka** [comment]
_loffset_ is only 54 bits, so safe within 64 bits. Any chance you are doing this with a 32-bit dd?

**Comment by cab404** [comment]
> _loffset_ is only 54 bits, so safe within 64 bits. Any chance you are doing this with a 32-bit dd?

That would be strange .-. 

```
[nix-shell:~]$ cat test.c
#include <stdio.h>
#include <stdint.h>

void main() {
   printf("int  %ld\n", sizeof(int));
   printf("long %ld\n", sizeof(long));
   printf("max  %ld\n", sizeof(uintmax_t));
}

[nix-shell:~]$ ./a.out
int  4
long 8
max  8
```

I will probably add logging to dd command, so we won't guess.

**Comment by cab404** [comment]
``` bash
dd if=/dev/1/docker of=xfs_undeleted/181 bs=4096 skip=86 seek=0 count=1 conv=notrunc status=none
dd if=/dev/1/docker of=xfs_undeleted/181 bs=4096 skip=0 seek=12501996963627008 count=0 conv=notrunc status=none
dd: xfs_undeleted/181: cannot seek: Value too large for defined data type
```

**Comment by cab404** [comment]
Yet it doesn't fail on that one:
```
dd if=/dev/1/docker of=xfs_undeleted/376273 bs=4096 skip=0 seek=140749818134528 count=0 conv=notrunc status=none

Recovered deleted inode 376273.
```

**Comment by ianka** [comment]
My guess it's blocksize*seek then. That's 54+12=66 bits.

**Comment by ianka** [comment]
The limit dd can handle is actually 2**63-2 bytes.

I added another sanity check. Please test it.

**Comment by cab404** [comment]
Yeah, that looks a lot better. No dd messages whatsoever.
