### ISSUE TITLE
help recovering a large qcow2 file

### ISSUE THREAD

**Issue by mailinglists35** [ianka/xfs_undelete#51]
os: OL7.9

tcl:
tcllib-1.14-1.el7.noarch
tcl-8.5.13-8.el7.x86_64

app: latest release from github

I did a `mv` from this filesystem to a different system, then accidentally lost the one on destination. on source I see 6MB of a log file as filesystem activity after I `mv`-ed the file, nothing else has used the xfs filesystem

````
$ sudo xfs_info /dev/mapper/ol-home
meta-data=/dev/mapper/ol-home    isize=256    agcount=4, agsize=1264128 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=0        finobt=0, sparse=0, rmapbt=0
         =                       reflink=0
data     =                       bsize=4096   blocks=5056512, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
````

````
$ file -l | grep -i qcow
Strength =  70 : QEMU QCOW Image []
````

````
$ sudo ./xfs_undelete -l
bin application/octet-stream Binary data
txt text/plain               Plain Text
````

````
[user@srv xfs_undelete-14.0]$ sudo ./xfs_undelete  -t -3hour -i ""  /dev/mapper/ol-home
Starting recovery.
Recovered file -> xfs_undeleted/2024-06-03-16-39_249.bin
Recovered file -> xfs_undeleted/2024-06-03-16-39_252.bin
Recovered file -> xfs_undeleted/2024-06-03-16-39_40519878.txt
Recovered file -> xfs_undeleted/2024-06-03-17-59_41781571.txt
Recovered file -> xfs_undeleted/2024-06-03-16-25_60678479.txt
Recovered file -> xfs_undeleted/2024-06-03-18-02_60680223.txt
Recovered file -> xfs_undeleted/2024-06-03-18-02_64116153.txt
Done.
[user@srv xfs_undelete-14.0]$ ls -lahtrs xfs_undeleted/
total 364K
4.0K drwxrwxr-x. 3 root root 4.0K Jun  3 18:15 ..
 36K -rw-r--r--. 1 root root  44K Jun  3 18:24 2024-06-03-16-39_249.bin
 84K -rw-r--r--. 1 root root 208K Jun  3 18:24 2024-06-03-16-39_252.bin
220K -rw-r--r--. 1 root root 284K Jun  3 18:24 2024-06-03-16-39_40519878.txt
4.0K -rw-r--r--. 1 root root 3.5K Jun  3 18:24 2024-06-03-17-59_41781571.txt
4.0K -rw-r--r--. 1 root root   13 Jun  3 18:24 2024-06-03-16-25_60678479.txt
4.0K -rw-r--r--. 1 root root   13 Jun  3 18:24 2024-06-03-18-02_60680223.txt
4.0K drwxr-xr-x. 2 root root 4.0K Jun  3 18:24 .
4.0K -rw-r--r--. 1 root root   13 Jun  3 18:24 2024-06-03-18-02_64116153.txt

````

is there any chance to recover that 12GB qcow2 file?

**Comment by ianka** [comment]
That 12GB file likely is a sparse file with many extents. In that case the extent list is stored in extra blocks. It could be that those bin files xfs_undelete recovered contain the real extent records. But xfs_undelete at the moment has no provisions to recover the file from those records.

So I think you need a different tool for recovering that file that is more sophisticated. I'm sorry.

**Comment by mailinglists35** [comment]
yes, it definitely was a sparse file, I am pretty sure I used the sparse flag initially when I copied it to xfs. thank you for the answer!

side question:
I have done this: `mv /xfs/file.qcow2 /ext4/file.qcow2`
then on ext4 I did a `rsync /other/path/ /ext4/` which changed `file.qcow2` to a symlink that was in `/other/path/` with same name to `/xfs/file.qcow2`, but that now was no longer in `/xfs/` :(
now when I run ext4magic on ext4 filesystem, it does only show the symlink, but not the old file. the filesystem is mounted with discard option, so if I unmount it, I suspect the blocks will get discarded down to the storage. any ideas what could I do at ext4 level to recover it?

**Comment by ianka** [comment]
**WARNING: I don't know whether this triggers the TRIM operation.**

If it does not, you could remount the ext4 filesystem without the discard option:

`# mount -oremount,nodiscard /ext4`

**Comment by ianka** [comment]
You haven't replied for a while. I'm closing this issue. Feel free to re-open if you  have new information.

**Comment by mailinglists35** [comment]
yes I believe the sparseness of the file prevented the recovery. even tried trials of paid commercial recovery tools. also could not recover it from ext4 neither.
