### ISSUE TITLE
/usr/bin/env: ‘tclsh’: No such file or directory ...

### ISSUE THREAD

**Issue by Albretch** [ianka/xfs_undelete#52]
Basically I would like to undelete a folder in an XFS partition, but  I am getting errors message:

"/usr/bin/env: ‘tclsh’: No such file or directory"

 which I don't know how to troubleshoot.

$ uname -a 
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
$ 

$ ls -l
total 256
drwxr-xr-x 2 user user 131072 Mar 18 14:40 xfs_undelete-master
-rwxr-xr-x 1 user user  28268 Jul 16 01:55 xfs_undelete-master.zip

$ ls -l xfs_undelete-master.zip 
-rwxr-xr-x 1 user user 28268 Jul 16 01:55 xfs_undelete-master.zip

$ file --brief xfs_undelete-master.zip 
Zip archive data, at least v1.0 to extract

$ sha256sum --binary xfs_undelete-master.zip 
db66ef9ca37120407f6a692fe0d30492dba525e2446ee1a87e26d3d978b7e875 *xfs_undelete-master.zip

$ cd xfs_undelete-master

$ ls -l
total 640
-rwxr-xr-x 1 user user 35149 Mar 18 14:40 LICENSE
-rwxr-xr-x 1 user user 13411 Mar 18 14:40 README.md
-rwxr-xr-x 1 user user   150 Mar 18 14:40 shell.nix
-rwxr-xr-x 1 user user 21851 Mar 18 14:40 xfs_undelete
-rwxr-xr-x 1 user user  9698 Mar 18 14:40 xfs_undelete.man

$ ls -l xfs_undelete
-rwxr-xr-x 1 user user 21851 Mar 18 14:40 xfs_undelete

$ file --brief xfs_undelete
Tcl script, UTF-8 Unicode text executable

$ sha256sum --binary xfs_undelete
063dad87b4f4ae505521735067405b07eb668e4fc7791624132420b665adb64a *xfs_undelete
$ 

$ sudo ./xfs_undelete --help
/usr/bin/env: ‘tclsh’: No such file or directory

$ ./xfs_undelete --help
/usr/bin/env: ‘tclsh’: No such file or directory

$ ./xfs_undelete
/usr/bin/env: ‘tclsh’: No such file or directory

$ sudo ./xfs_undelete
/usr/bin/env: ‘tclsh’: No such file or directory

**Comment by ianka** [comment]
As written in the Prerequisites section of the README, you need tcl-8.5 or later and tcllib to run this script.

**Comment by ianka** [comment]
You haven't replied for a number of days so I close this issue. Feel free to reopen it if your problem persists.
