### ISSUE TITLE
Time stamp off by 26 years

### ISSUE THREAD

**Issue by otibsa** [ianka/xfs_undelete#54]
I tried to use `xfs_undelete` to recover some file on my Unraid server after a user error. It did not find anything to recover when using a time range (the files were deleted today, so I wanted to recover anything deleted since yesterday):

```
# xfs_undelete -t 2024-07-18 -o /mnt/temp/sdd1/undeleted/ /dev/sdc1
Starting recovery.
Done.
```

However, when I specify no time range (or `-t 1998-07-18`), I get recovered files:
```
# xfs_undelete -o /mnt/temp/sdd1/undeleted/ /dev/sdc1
Starting recovery.
Recovered file -> /mnt/temp/sdd1/undeleted/1998-07-18-23-07_196.mp4
...
Recovered file -> /mnt/temp/sdd1/undeleted/1998-07-18-23-07_200.matroska
...
# date
Fri Jul 19 19:12:14 CEST 2024
```

The date is wrong (this server did not exist in 1998). Any idea what the problem is?

**Comment by ianka** [comment]
Oh wow. That's a cool failure pattern.

Could you change [line 261 of the script](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L261) of the script into

     set of [file join [dict get $::parameters o] [format "%s_%s_%s" $ctime [clock format $ctime -format "%Y-%m-%d-%H-%M"] $inode]]

and run it again? That gives us the raw value of the “ctime” value stored in the recovered inode along with what Tcl's [clock format] thinks what that number means in a human-readable form.

**Comment by otibsa** [comment]
Thanks for the quick response!

Here's the output
```
# xfs_undelete -t 1998-07-18 -o /mnt/temp/sdd1/test/ /dev/sdc1
Starting recovery.
Recovered file -> /mnt/temp/sdd1/test/900796072_1998-07-18-23-07_196.mp4
^C
```

**Comment by ianka** [comment]
Well … on my machine and with the `date` tool instead of Tcl this looks the same:

    $ date -d@900796072
    Sa 18. Jul 23:07:52 CEST 1998

So it can't be a problem with the conversion. I wonder *why* “ctime” is this number `900796072`. Maybe the inode format in your XFS doesn't have the ctime in the bytes 48..51 as assumed in [line 251](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L251). I have to find more information on that.

**Comment by ianka** [comment]
I found there's an XFS feature called “bigtime” that  [changes the meaning of the timestamps in the inode](https://github.com/torvalds/linux/blob/master/fs/xfs/libxfs/xfs_format.h#L711-L791). Could you please check whether your filesystem has that option activated?

    $ xfs_info /dev/sdc1 | grep bigtime

**Comment by ianka** [comment]
[I have just added support for the “bigtime” feature of recent XFS in the wild](https://github.com/ianka/xfs_undelete/commit/7e19828923248bed605434f1df352b23bca252dc).

Please try again with the latest version and give me a short reply whether that fixes your problem.

**Comment by otibsa** [comment]
Yep, `bigtime` is enabled
```
# xfs_info /data | grep bigtime
         =                       reflink=1    bigtime=1 inobtcount=1 nrext64=0
```

And after your patch, it detects the correct time stamp:
```
# tclsh xfs_undelete_bigtime -o /mnt/temp/sdd1/test_bigtime/ /dev/sdc1
Starting recovery.
Recovered file -> /mnt/temp/sdd1/test_bigtime/2024-07-19-18-20_196.mp4
^C
```

Thanks for the quick work! :+1:

**Comment by ianka** [comment]
I close this as resolved then. Is it the same files [this other user wanted to recover two days ago?](https://github.com/ianka/xfs_undelete/issues/53)

**Comment by ianka** [comment]
Thank you for pointing out this problem.
