### ISSUE TITLE
can't find package cmdline

### ISSUE THREAD

**Issue by tomachinz** [ianka/xfs_undelete#55]
I'm on Kubuntu 24, downloaded the zip, expanded it, ran ./xfs_undelete and get

```
can't find package cmdline
    while executing
"package require cmdline"
    (file "./xfs_undelete" line 10)
```
So I tried to install cmdline 
```
 sudo apt install cmdline
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cmdline
```
Seems like I need to install some dependencies, not sure how to do that.

**Comment by ianka** [comment]
That tcl package _cmdline_ is usually part of the larger **_tcllib_** package of your Linux distribution. As stated in the README.

**Comment by Metamorphus** [comment]
Having the same issue on Amazon Linux 2. tcllib installed (from yum), version tcllib-1.14-1.el7.noarch
In tclsh console the error is the same. Please help

**Comment by ianka** [comment]
Check it manually then.

    $ tclsh <<<'package require cmdline'
    $

This should return without an error message. If it doesn't there's a problem with that tcllib package. Maybe it installs the files where tclsh can't find it? Check with

    $ tclsh <<<'puts [join $auto_path \n]'
    /usr/lib64/tcl/tcl8.6
    /usr/lib64/tcl
    /usr/lib
    /usr/share/tcl
    $

The result of

    $ rpm -ql tcllib

must show that the files are installed under one of those dirs in `auto_path` on your machine.

**Comment by Metamorphus** [comment]
Thank you, auto_path indeed did not contain the directory with package. Adding it manually on top of the script resolved my issue

**Comment by ianka** [comment]
I close this as resolved.

**Comment by tomachinz** [comment]
Ah yes! Thanks Lanka! I was able to recover my files with xfs_undelete including filenames which is great.

**Comment by mkot02** [comment]
just for reference if anyone needds it in the future: in RHEL9 tcllib package is in epel repository
