### ISSUE TITLE
agcount value

### ISSUE THREAD

**Issue by tirear** [ianka/xfs_undelete#6]
Hello,

There is a variable called "agcount" in the script xfs_undelete. The default value is 4. This is not updated through reading the superblock. The value of my filesystem is 32. With the default value 4, I cannot get the lost file and then the script stopped too early. By the way, I get the value 32 by executing the command "xfs_info". Hope this will help improve this nice work!

Thanks

**Comment by ianka** [comment]
Thank you for finding this bug.

Fixed in v6.2.
