### ISSUE TITLE
Root privileges aren't really required for block devices

### ISSUE THREAD

**Issue by dcoshea** [ianka/xfs_undelete#8]
If the script is passed a block device, it tries to remount it readonly, and if it gets the error `mount: only root can use "--options" option` from the `mount` command, it reports `Root privileges are required to run this command on devices.`

However, it is possible to have access to a block device, for example due to being a member of the "disk" group, while not having the right to mount/remount that device, so this is unnecessarily restrictive.

This is probably not the case for most users, but it would be nice if it was supported.  Perhaps to keep the script "friendly", if the open of the filesystem fails due to access being denied, the script could expand on the error to suggest that the user might need to run it as root.

This is trivial to work around by commenting out the `exit`.

**Comment by ianka** [comment]
> However, it is possible to have access to a block device, for example due to being a member of the "disk" group, while not having the right to mount/remount that device, so this is unnecessarily restrictive.

You are missing an important detail here. Xfs_undelete does not deal with the journal of the filesystem and thus, it __must__ umount the device or remount it read-only so the filesystem is in a clean state before any recovery is attempted.

If you skip this step, it's likely you cannot recover the file you deleted accidentally just ten minutes ago. And that's the most common case.

**Comment by dcoshea** [comment]
My procedure was to unmount the filesystem first because I didn't want to risk any overwriting of the deleted data, then go searching for a tool to do the undelete, so it was already unmounted.  I understand that the script should make sure it's not mounted, but if it's already unmounted then there is technically no need for the user to have the right to [re]mount it.

**Comment by ianka** [comment]
Okay, I see a use case: the admin remounts the filesystem read only and then asks the users to run the tool themselves. I add a check whether the filesystem is already read only or umounted before the remount attempt, though it isn't atomic then.

**Comment by ianka** [comment]
fixed in v7.2

**Comment by dcoshea** [comment]
Thanks!  I think it was already not exactly atomic: someone could now mount the filesystem between the check and unmount, but even before this change someone could mount the filesystem between the unmount and open, couldn't they?  In fact, couldn't someone mount it while the script is running?  I don't imagine fsck or other such tools prevent this so I wouldn't feel too bad about it :)

**Comment by ianka** [comment]
> someone could mount the filesystem between the unmount and open,

Yes, but it would still be clean regarding the deleted files then. If there was a system call or ioctl() that makes the xfs driver clean the journal without remounting, I would have used that one. But there isn't.
