### ISSUE TITLE
problem recovering a txt file

### ISSUE THREAD

**Issue by ltgentoo** [ianka/xfs_undelete#9]
I create a txt file with three lines：
**11
12
13**
the i delete this file,and use this tool to undelete it,it works fine ,but the file content is a little different:
![11](https://user-images.githubusercontent.com/7405793/79176807-d0d0d400-7e33-11ea-865a-72d5e8d813d2.png)

**Comment by ianka** [comment]
As I had put it in on the front page

> **Limitations**
> The way XFS deletes files makes it impossible to retrieve the correct file size. Most files will be padded with zeroes so they fit the XFS block size. Most programs do not bother anyway.

Those ^@ you see is how vi displays binary zero characters. The file is padded to the next XFS block boundary with those zeroes. There's unfortunately no way around this as XFS clears the file length field on deletion, and the extents length is only at block granularity.

**Comment by ianka** [comment]
I've added a feature to have xfs_undelete trim those trailing zeroes by default in all files of the text/* mimetype. Please see v8.0 and read the manpage, too.
